### ISSUE TITLE
Group field reference has unfriendly usage

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/react-advanced-form#172]
## What
Need to find a way for friendly usage of `fields` for grouped fields.

## Why
Grouped fields are stored as `fields[groupName.fieldName] = fieldProps` in internal state. That is needed for easier referencing using Immutable during the form's lifecycle.

## How
* Destruct the `fields` to have a proper structure (`fields.groupName.fieldName`)?

## Roadmap
- [x] Store the grouped fields in the `form.state.fields` as nested Object keys
- [x] Refine reactive utils to be usable with the new reference model (introduce `subscribe`)
- [x] Refine the validation, since the iteration algorithm should change
- [x] Refine the serialization to return a properly serialized fields
- [x] Update unit tetst
- [x] Update integration tests
- [x] Update the documentation of "Reactive props"

**Comment by kettanaito** [comment]
Historically, glued Object key for grouped fields was introduces to simplify the iterations of the `fields` Map/Object, for example, during the serialization. If you split the fields like so:

```js
{
  groupName: {
    fieldName: FieldRecord
  }
}
```

Maintaining the Map structure of this kind would be troublesome. It would mean a recursive iteration unless the `FieldRecord` is found, which I think should be avoided performance-wise.

Having the `{ 'groupName.fieldName': FieldRecord }` structure also simplifies the serialization, as glued key can be split into an array by its separator (".") and provided to `Iterable.set()`.

**Comment by kettanaito** [comment]
The changes are ready to be merged.

I would like to spend some time thinkin on the interface of reactive props. I don't like to merge each interface change under minor versions, as it creates a lot of versions of the library with completely obsolete interface. Instead, I think we should dedicate time and think through a good interface just once.

**Comment by kettanaito** [comment]
Fields architecture was re-designed and now allows to have proper references:

```js
fields.groupName.fieldName
```

Merged into [`1.0`](https://github.com/kettanaito/react-advanced-form/tree/1.0) pre-release branch. Closing.
