### ISSUE TITLE
Use RxJS to update reactive (dynamic) props

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/react-advanced-form#24]
## What
Need to have the fields with dynamic props to update the latter once their dependency changes in real time.

## Why
Having the obsolete state of the field results into bad UX when using the forms.

## Test scenario
Consider this form:
```jsx
<Form>
  <Field.Input name="username" />
  <Field.Input name="password" required={({ fields }) => fields.username && !!fields.username.value} />
</Form>
```
The above reads as "password field is required once username field has value". This works gracefully, however:
1. Enter some value into "username".
2. Try to submit the form.
3. See the error under "password", since its dynamic `required` resolved to true (username has value).
4. Remove the value from "username".
5. See "password" still showing the "required" error.

## Expected behavior
1. "password" should immediately update its dynamic prop based on the changes of its dependants.
2. The error message beneath "password" should disappear after the dynamic prop (`required`) resolve to `false`. This will be achieved automatically once # 1 is done.

## How
* It would be nice to determine the dynamic prop's dependancies (fields) and update it once the latter are changed. However, I don't see a way for this to work since dynamic props are functions returning an expected prop value. There is no sane way of determining what would happen in the uncontrolled function.
* Therefore, makes sense to update required props on `Form.updateField`, as a callback of the method.

## Roadmap
- [x] Create a unified interface for field's props change subscriptions
- [x] Dispatch props changed event when the field's props change (specific props monitoring or props diff)
- [x] Allow to subscribe to multiple props changes of multiple fields
- [x] Resolve reactive props upon the subscriber field registration
- [x] Create efficient `rxUtils` to manage observers and subscriptions
- [x] Resolve reactive props when the subscribed field is not yet registered (i.e. rendered conditionally). Delegated subscriptions?
- [x] Subscribe to the changes of props important for the field's record (keep field record in sync with the changing dependent props)
- [x] Write integration tests

**Comment by kettanaito** [comment]
Temporary implementation is merged under #39, **however**, the way it's written is inefficient.

Iterating through each fields on *any* update, calling `Form.validateField()` is not a proper solution. We might need to look into the RxJS, or similar things to achieve this.

**Comment by kettanaito** [comment]
## Update
Moved to Release 2.0 milestone, since this is not a blocker to reach 1.0, but rather an improvement point.

**Comment by kettanaito** [comment]
## Concept
It should be possible to create Observables using `RxJS` in the following way:

**createField.componentWillReceiveProps/componentWillUpdate:**
```jsx
/* Get the Map of props subscriptions */
const { propsSubscriptions } = this.context;

/* Find a subscription to the currently updated field */
const relativeSubscriptions = propsSubscriptions.filter((subscription) => {
  return (subscription.get('subscribedTo') === this.props.name);
});

if (relativeSubscriptions.empty()) return;

relativeSubscriptions.forEach((subscription) => {
  subscription.Observable;
});
```

**Comment by kettanaito** [comment]
An idea suggested about has passed the first PoC and has proven itself worthy.

I will continue on that, and most likely this feature will be packed in `1.0`!

**Comment by kettanaito** [comment]
## Roadmap
- [x] Compose `this.state.subscriptions` on `Form.registerField()`
- [x] Dispatch conditional prop change events on `Field.componentWillUpdate()`
- [ ] Add support for multiple subscribed props
- [ ] Resolve dynamic props initially, on `Form.registerField()` or even `Field.registerWith()`
- [ ] Bypass functional props which are not RxProps subscriptions
- [ ] Write integration tests

**Comment by kettanaito** [comment]
The following interface was suggested by @Vidlec:

```jsx
<Input name="first" />

<Input
  name="second"
  required={({ form }) => {
    return form.subscribe(['first', 'third'], ({ first, third }) => {
      return (first.value === 'foo') && (third.type === 'password');
    });
  } } />
```

**Comment by kettanaito** [comment]
## Blockers
- [ ] Create an efficient interface to subscribe to field props changes, including subscriptions to multiple fields and multiple props
- [ ] Create an efficient set of `rxUtils` to create and manage props observables
- [ ] Figure out how to resolve rx-props in case the subscribed field is not yet mounted (mounts conditionally after some time). Create a delegated subscription to resolve once the subscribed field is mounted?

**Comment by kettanaito** [comment]
# Interface requirements
* Must be easy to declare
* Must allow subscriptions to one/multiple props of one field
* Must allow subscriptions to one/multiple props of multiple fields
* Must allow precise updates of the dynamic props when the subscribed props change

**Comment by kettanaito** [comment]
Defining a single interface for props subscriptions was a huge mess.

Considering two major options right now, I am leaning toward the combination of two. It's possible to use a `Proxy` over the `fields` to find out which fields are accessed in the reactive prop resolver function, therefore, it's possible to create an observable for that accessed field. And using observables it's possible to listen to that field's changes and re-resolve the reactive prop.

**Caveats:**
1. How to proxy immutable `fields`? Must be possible, but not clear at the moment.

**Comment by kettanaito** [comment]
Merge and release is planned for tomorrow.

**Comment by kettanaito** [comment]
Merged and published under [`0.20.0`](https://github.com/kettanaito/react-advanced-form/commit/8d5832ab70c4bb1a3f337262dfbc17947aa76302). Closing.
