### ISSUE TITLE
Bundle size reduction roadmap

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/react-advanced-form#253]
# Roadmap
## Bundling
- [ ] Ensure proper tree shaking
- [ ] Ensure Flow types are stripped in the production bundle
- [ ] Ensure Ramda methods are imported explicitly, without unnecessary code
- [ ] Ensure any kind of useless comments are stripped out in the production bundle

## Architecture
- [ ] See if writing custom PropTypes validator for `Immutable.Map` results into smaller bundle size
- [ ] Replace Ramda's `ifElse` and other simple methods with plain JavaScript
- [ ] Remove `invariant` from the internal methods
- [ ] Replace Form handlers with references to composite functions

**Comment by Vidlec** [comment]
Regarding Ramdas ifElse: https://github.com/ramda/ramda/blob/v0.25.0/source/ifElse.js
Not sure if it can be made significantly smaler. Also thats only 1.3kb not minified

**Comment by kettanaito** [comment]
@Vidlec I've tried replacing Ramda's method with identical one, except those don't have currying, and in average they are at least half smaller the size of the original Ramda methods.

That is, of course, subjective, but I've put it there to be considered.

**Comment by kettanaito** [comment]
@Vidlec, after some time I also came to conclusion that micro-optimization is not worth it. I would stick with Ramda's functions.

**Comment by kettanaito** [comment]
Ditching ImmutableJS (#272) will also affect the bundle size.

**Comment by kettanaito** [comment]
Proper imports of `ramda` (or the usage of `babel-pluing-ramda`) reduces the library's bundle size by  ~50Kb.
