### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/react-advanced-form#257]
## What
We need to ensure React Native support of React Advanced Form.

## Why
To have this library working on React Native.

## How
How to reproduce the issue? / How do you see the implementation of the feature?

## Roadmap
- [ ] `prop-types` package throws an error `Unable to resolve module "./factoryWithThrowingShims"`, trying to resolve the module from the build directory.
- [ ] Cover changes in API of TextInput (i.e. `onChangeText` event).
- [ ] Cover the absence of a `form` tag in React Native.
