### ISSUE TITLE
Consider removing Immutable JS from peer dependencies

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/react-advanced-form#272]
## Environment
* **react-advanaced-form:** 1.4.0

## What
I have received a valuable suggestion to remove ImmutableJS as a peer dependency of the library.

## Why
* Forcing is bad, generally
* ImmutableJS is a rather large package to be forced to install
* People that have no experience/don't use ImmutableJS will have no benefit of having it as a peer dependency. ImmutableJS is primarily used in the library's internals. Those can be re-written.
* It is a valid reason against bringing RAF to new projects
* ImmutableJS is also troublesome to type annotate

## How
* Remove it completely, and preserve immutability by sane code and built-in methods
* Re-write ImmutableJS interfaces with native functions and Ramda (i.e. "path" instead of "getIn")

## Roadmap
- [x] Add a deprecation warning when attempting to use `withImmutable`. Since these changes are going to be release in the next minor update, we can't just cut the functionality without at least warning it being deprecated.
- [x] Use plain object for `fields`
- [x] Use plain object for validation `rules`
- [x] Use plain object for validation messages

**Comment by kettanaito** [comment]
Since this is a big internal change, it should be taken as a rule that **no upcoming changes rely on ImmutableJS instances and their interfaces**.

That being said, I am already replacing `x.getIn` with `path` from Ramda, which saves a lot of computing power ditching `fromJS()` conversions of accepted props.

**Comment by kettanaito** [comment]
I am starting this gradually with #245 by replacing any references to immutable data structures with Ramda functions. That is mainly for interface purpose for deep key reference in objects.

**Comment by kettanaito** [comment]
I can't help but comment how smooth migration from immutable to ramda is!

Maybe this will be helpful:

```
setIn --> assocPath
getIn --> path
mergeDeep --> mergeDeepLeft/mergeDeepRight
```

**Comment by kettanaito** [comment]
Added a deprecation warning https://github.com/kettanaito/react-advanced-form/commit/144bc2a61b1e14bf1007f98c461ef786233a93ce. Closing.
