### ISSUE TITLE
Update package dependencies

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/react-advanced-form#284]
## Environment
* **react-advanaced-form:** 1.4.1

## Roadmap
- [x] Update to `rxjs@6.x`
- [x] Update `webpack@4.x`
- [x] Update `babel@7.x`
- [ ] Update to `cypress@3.x`
- [ ] Update Jest tests to work with `babel@7.x` (https://github.com/facebook/jest/pull/6949)
- [ ] (Optional) Adjust Storybook webpack config
- [ ] (Optional) Adjust Cypress webpack config
