### ISSUE TITLE
Update the documentation

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/react-advanced-form#288]
## Environment
* **react-advanaced-form:** 1.5.0

## Roadmap

- [x] Architecture / Controlled fields
- [x] Getting started / Creating fields
- [x] Validation / Getting started
- [x] Validation / Validation schema / Reactive rule
- [x] Validation / Validation messages

**Comment by kettanaito** [comment]
Documentation has been updated, yet not all sections were finished.
